# Generated by Django 4.2.6 on 2023-11-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_symbol', models.CharField(max_length=5)),
                ('date_selected', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Stonk',
        ),
    ]
