# Generated by Django 4.1.7 on 2023-12-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_userstock_delete_stonk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstock',
            name='date_selected',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
